export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const REGISTER_COMPLETE_REQUEST = 'REGISTER_COMPLETE_REQUEST';
export const REGISTER_COMPLETE_SUCCESS = 'REGISTER_COMPLETE_SUCCESS';
export const REGISTER_COMPLETE_ERROR = 'REGISTER_COMPLETE_ERROR';

export const LOGGED_IN_USER_REQUEST = 'LOGGED_IN_USER_REQUEST';
export const LOGGED_IN_USER_SUCCESS = 'LOGGED_IN_USER_SUCCESS';
export const LOGGED_IN_USER_ERROR = 'LOGGED_IN_USER_ERROR';

export const FORGOT_PASSWORD_USER_REQUEST = 'FORGOT_PASSWORD_USER_REQUEST';
export const FORGOT_PASSWORD_USER_SUCCESS = 'FORGOT_PASSWORD_USER_SUCCESS';
export const FORGOT_PASSWORD_USER_ERROR = 'FORGOT_PASSWORD_USER_ERROR';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_ADMIN_REQUEST = 'GET_ADMIN_REQUEST';
export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS';
export const GET_ADMIN_ERROR = 'GET_ADMIN_ERROR';

export const LOGIN_GOOGLE_REQUEST = 'LOGIN_GOOGLE_REQUEST';
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS';
export const LOGIN_GOOGLE_ERROR = 'LOGIN_GOOGLE_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
